### ISSUE TITLE
Support array of hex strings in ColorAccessor trait

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/lonboard#149]
- numpy array of strings that all start with `#`

**Comment by vincentsarago** [comment]
👋 https://github.com/cogeotiff/rio-tiler/blob/main/rio_tiler/colormap.py#L205-L264

**Comment by kylebarron** [comment]
🫣 https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.to_rgba_array.html

**Comment by vincentsarago** [comment]
yeah, in rio-tiler we didn't want to add Matplotlib dependency just for this 😄

**Comment by kylebarron** [comment]
Yeah... I currently already have a matplotlib dependency because I wanted to use [`LinearSegmentedColormap`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.LinearSegmentedColormap.html). It also integrates well with the [palettable](https://github.com/jiffyclub/palettable).

We might try to vendor some functionality in the future, but all the utilities in `matplotlib.colors` are so useful that for a plotting library maybe a dependency on mpl is ok...

**Comment by kylebarron** [comment]
I'm going to close this, pointing people to use `to_rgba_array` themselves if desired
