### ISSUE TITLE
Add polygon edge colours to non-extruded polygons

### ISSUE THREAD

**Issue by robintw** [developmentseed/lonboard#197]
I've just discovered lonboard and I love how fast it is!

I'm currently trying to visualise a set of polygons that all border each other. When viewed in lonboard, they merge together and look like one big polygon:
<img width="810" alt="image" src="https://github.com/developmentseed/lonboard/assets/296686/14bc5e39-9f7d-4a0d-a0fc-00dcc22ad0b2">

I've tried fiddling with setting `get_line_color`, but that seems to require `extruded=True` which I don't really want to use. Even if I do use `extruded=True` then I can't see lines around the edges of the polygons. For this I was using the following call:

```
viz(gdf, get_fill_color='red', get_elevation=1, extruded=True, opacity=0.5, get_line_color='black')
```

and I get something like this:

<img width="726" alt="image" src="https://github.com/developmentseed/lonboard/assets/296686/5061f32b-992e-48e7-9a78-7e54076a45db">

I could be using this wrong - so feel free to correct me if it's just a mistake on my end.

**Comment by kylebarron** [comment]
You're not using it wrong! 

In the JS side of deck.gl, there's both a [`SolidPolygonLayer`](https://deck.gl/docs/api-reference/layers/solid-polygon-layer) and a [`PolygonLayer`](https://deck.gl/docs/api-reference/layers/polygon-layer). The difference being that the latter will render under the hood both a `SolidPolygonLayer` for the polygon interior and a `PathLayer` for the exterior.

In deck.gl-layers, we haven't implemented a `GeoArrowPolygonLayer` yet (ref https://github.com/geoarrow/deck.gl-layers/issues/61). Once we do, we can expose a `PolygonLayer` here in lonboard and point most people to that layer.

A workaround for now is to create the polygon exteriors yourself using e.g. https://shapely.readthedocs.io/en/stable/reference/shapely.get_exterior_ring.html and then render both a `PathLayer` and a `SolidPolygonLayer` yourself, you should be able to recreate what a `PolygonLayer` will do in the future.

**Comment by robintw** [comment]
Thanks for the very helpful response. I'll make my own little function that returns both a PathLayer and a SolidPolygonLayer for the moment.
