### ISSUE TITLE
Clean up memory after closing Map or stopping/restarting the python process

### ISSUE THREAD

**Issue by jorisvandenbossche** [developmentseed/lonboard#198]
When visualizing a large dataset, the browser tab (or GPU memory) can hold a lot of memory, which isn't cleaned up by restarting the python process (testing this in a notebook, and so restarting the kernel). 
Also explicitly calling `map.close()` or `map.close_all()` doesn't seem to help. Only actually closing the browser tab does clean up the memory. 

Testing this using Firefox.

**Comment by jorisvandenbossche** [comment]
(for Chrome I see the same behaviour)

**Comment by kylebarron** [comment]
I think this might be Jupyter behavior where it separates frontend views from the Python lifecycle. So restarting _python_ won't remove memory, but removing a _cell_ will close the view.

Linking to a thread on discord by @kolibril13 https://discord.com/channels/1178781616714297576/1178781617230200886/1211440320470974576

> Just made some experiments using the anywidget "cleanup" function, and got some findings, hope this knowledge is useful for someone.
> The docs say "[cleanup is] executed any time the view is removed from the DOM." https://anywidget.dev/en/getting-started/
> Here I found 3 cases where the cleanup function was called in JupyterLab:
> 1. Closing a notebook tab
> 2. Running a cell again and overwriting the previous widget view.
> 3. Pressing the "Clear all outputs of all cells" button
> Additionally, if one widget is displayed in multiple cells, Clear all outputs  will also run the cleanup function multiple times.
> ```py
> import anywidget
> import traitlets
> 
> class CounterWidget(anywidget.AnyWidget):
>     _esm = """
>     function render({ model, el }) {
>         console.log("Hello World");
> 
>       let getCount = () => model.get("count");
>       let button = document.createElement("button");
>       button.innerHTML = `count is ${getCount()}`;
>       button.addEventListener("click", () => {
>         model.set("count", getCount() + 1);
>         model.save_changes();
>       });
>       model.on("change:count", () => {
>         button.innerHTML = `count is ${getCount()}`;
>       });
>       el.appendChild(button);
>         return () => {
>         console.log("cleanup");
>         };
>     }
>     export default { render };
> 
>     """
>     count = traitlets.Int(0).tag(sync=True)
> 
> counter = CounterWidget()
> counter
> ```

**Comment by kylebarron** [comment]
I don't think there's anything on my side I can change here, so I'll close this.
