### ISSUE TITLE
maps are blank

### ISSUE THREAD

**Issue by sabman** [developmentseed/lonboard#245]
Thanks for the awesome project. I am just trying it out on my mac
```
➜ uname -a
Darwin terrier.fritz.box 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 arm64
```

```
➜ pip show lonboard
Name: lonboard
Version: 0.4.1
Summary: Python library for fast, interactive geospatial vector data visualization in Jupyter.
Home-page:
Author: Kyle Barron
Author-email: kyle@developmentseed.org
License: MIT
Location: /Users/shoaib/.pyenv/versions/3.8.12/envs/venv3_8_12/lib/python3.8/site-packages
Requires: anywidget, geopandas, matplotlib, palettable, pandas, pyarrow, shapely
Required-by:
```

I don't have geoparquet installed I assume that's expected coz lonboard has its own version of it.
```
➜ pip show geoparquet
WARNING: Package(s) not found: geoparquet
```

I tried 3 of the examples none show the map layers. 
![migration_ipynb](https://github.com/developmentseed/lonboard/assets/1907/767c3dd2-08d4-4d55-88ef-c6fdbd178ffb)

I'm gonna check for debug options also on a different architecture next but any pointers would be great!

**Comment by kylebarron** [comment]
with 0.4.1 I can still see stuff rendered

<img width="753" alt="image" src="https://github.com/developmentseed/lonboard/assets/15164633/24195b8a-22b8-4158-8b26-99eea9d6381d">

```
virtualenv env
source ./env/bin/activate
pip install jupyterlab lonboard
python -m ipykernel install --user --name "$(basename "$PWD")"
./env/bin/jupyter lab
```

you might want to look in the console.

alternatively, the issue might just be that the example you're looking at explicitly _won't render_ aside from hovering your cursor over the map. So you need to hover over the US to visualize the Arcs

**Comment by kylebarron** [comment]
Actually can you try 0.3.0? It seems I do have some issues still in 0.4.1

**Comment by kylebarron** [comment]
Could you try again with 0.4.2? Thanks!
