### ISSUE TITLE
Fix CSS in static HTML export

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/lonboard#248]
Given default fonts, presumably css is not getting added to the static HTML page

<img width="840" alt="image" src="https://github.com/developmentseed/lonboard/assets/15164633/573a3be2-a686-482c-8160-3609c9392d76">

**Comment by giswqs** [comment]
This issue might be relevant: https://github.com/opengeos/leafmap/issues/594#issuecomment-1807013768

**Comment by kylebarron** [comment]
I don't think that's related. The standalone html export is working fine here; it's just missing our css.

**Comment by giswqs** [comment]
Never mind. The exported html doesn't work with Streamlit. I will look into it later.

**Comment by kiasari** [comment]
@giswqs Could you find a way to display the `Map` object in Streamlit?
