### ISSUE TITLE
Additive layer blending

### ISSUE THREAD

**Issue by jc9677** [developmentseed/lonboard#250]
It would be great to have the option to use additive layer blending mode. From an example on Peter Beshai's blog ([https://peterbeshai.com/blog/2019-08-10-deckgl-point-animation/](url)) :

> import GL from '@[luma.gl/constants](http://luma.gl/constants)';
const librariesLayer = new DelayedPointLayer({
  ...
  parameters: {
    // prevent flicker from z-fighting
    [GL.DEPTH_TEST]: false,

    // turn on additive blending to make them look more glowy
    [GL.BLEND]: true,
    [GL.BLEND_SRC_RGB]: GL.ONE,
    [GL.BLEND_DST_RGB]: GL.ONE,
    [GL.BLEND_EQUATION]: GL.FUNC_ADD,
  },
});

**Comment by kylebarron** [comment]
Customizing GL blending modes is really advanced, and I imagine the number of python users who would know how to use it is miniscule. I'd consider a PR but I don't think this is the highest priority for me to implement

**Comment by kylebarron** [comment]
This is so low level that I don't have an interest in exposing this for now. We can revisit in the future.
