### ISSUE TITLE
Comparison: keplergl-jupyter

### ISSUE THREAD

**Issue by DahnJ** [developmentseed/lonboard#256]
I think it would be great to provide a comparison to [keplergl-jupyter](https://docs.kepler.gl/docs/keplergl-jupyter) in the [Alternatives](https://developmentseed.org/lonboard/latest/alternatives/) section.

The goals seem quite similar: both libraries utilize deck.gl to create performant interactive visualizations of large-scale geospatial data in Jupyter notebooks. 

From what I can tell, there is a number of technological differences (Kepler is much less Python-native, no use of Wasm, use of Mapbox GL, not utilizing GeoParquet+GeoArrow) and Kepler has its own high-level API on top of deck.gl. 

Lonboard looks like a really cool project and it would be great to know more clearly what it can potentially offer to existing Kepler.gl users 🚀

**Comment by kylebarron** [comment]
I added a section in https://github.com/developmentseed/lonboard/pull/272. What do you think?

**Comment by DahnJ** [comment]
Looks great, thanks!
