### ISSUE TITLE
Trouble Displaying PathLayer

### ISSUE THREAD

**Issue by jwass** [developmentseed/lonboard#275]
I'm trying to display some LineStrings and having an issue where the map appears but there's nothing on it.

```
import geopandas as gpd
import shapely.geometry
from lonboard import Map, PathLayer

gdf = gpd.GeoDataFrame(
    {
        "geometry": [
            shapely.geometry.LineString(shapely.geometry.box(0.0, 0.0, 5.0, 5.0).exterior),
            shapely.geometry.LineString(shapely.geometry.box(40., 40., 45., 45.).exterior)
        ],
        "id": [0, 1],
    }
)

layer = PathLayer.from_geopandas(
    gdf,
    get_color=[255, 0, 0],
)

map_ = Map(layers=[layer])
map_
```
will display a map zoomed to the right bounds, but there are no lines displayed. I've tried making simpler lines rather than box exteriors and other color/alpha values but haven't gotten anything to display correctly.

<img width="1241" alt="Screenshot 2023-11-29 at 4 48 51 PM" src="https://github.com/developmentseed/lonboard/assets/1214350/76b9b561-515c-445f-933c-a63adee5fa2b">

If I create polygons it works fine:
```
import geopandas as gpd
import shapely.geometry
from lonboard import Map, SolidPolygonLayer

gdf = gpd.GeoDataFrame(
    {
        "geometry": [
            shapely.geometry.box(0.0, 0.0, 5.0, 5.0),
            shapely.geometry.box(40., 40., 45., 45.),
        ],
        "id": [0, 1],
    }
)

layer = SolidPolygonLayer.from_geopandas(
    gdf,
    get_fill_color=[255, 0, 0],
)

map_ = Map(layers=[layer])
map_
```
<img width="1253" alt="Screenshot 2023-11-29 at 4 47 25 PM" src="https://github.com/developmentseed/lonboard/assets/1214350/57cfc11b-f242-4552-9285-781cd29a3705">

```
>>> import lonboard
>>> lonboard.__version__
'0.4.2'
```

**Comment by giswqs** [comment]
get_line_color?

**Comment by jwass** [comment]
> get_line_color?

That's not what it expects.
`TypeError: unexpected keyword argument 'get_line_color'`

Also doesn't match the docs: https://developmentseed.org/lonboard/latest/api/layers/path-layer/#lonboard.PathLayer.get_color

**Comment by kylebarron** [comment]
Try `layer.width_min_pixels = 10` https://developmentseed.org/lonboard/latest/api/layers/path-layer/#lonboard.PathLayer.width_min_pixels

**Comment by kylebarron** [comment]
If you have suggestions on how to make this more clear, I'm open to them. Trying to figure out the line between simplicity and being true to the deck.gl API.

Maybe print a warning on the python side if `width_min_pixels` is set to `0` and `get_width` is not provided?

**Comment by kylebarron** [comment]
FWIW, the [current default](https://developmentseed.org/lonboard/latest/api/layers/path-layer/#lonboard.PathLayer.get_width) is that paths are rendered one-meter wide

**Comment by jwass** [comment]
> Try `layer.width_min_pixels = 10` https://developmentseed.org/lonboard/latest/api/layers/path-layer/#lonboard.PathLayer.width_min_pixels

That did it. Thank you!

> If you have suggestions on how to make this more clear, I'm open to them. Trying to figure out the line between simplicity and being true to the deck.gl API.

I definitely should have looked more closely at the docs. I'm not familiar with deck.gl which may have lead to some misunderstanding on my part too.

> Maybe print a warning on the python side if `width_min_pixels` is set to `0` and `get_width` is not provided?

That seems like it would be useful if someone else ends up doing the same thing.

In any case, this has worked out of the box and is super useful so far. Thanks!
