### ISSUE TITLE
Feature request: export to Protomaps? 

### ISSUE THREAD

**Issue by jaanli** [developmentseed/lonboard#352]
Lonboard is amazing for exploratory data analysis - thank you!

however, not sure how best to publish the results of an analysis. 

Would it be feasible to export a lonboard map to the protomaps pmtiles format? (E.g. for embedding interactively on a static website)

**Comment by kylebarron** [comment]
I think it's good to ideate on better ways to publish results, but trying to export to pmtiles would be a massive investment. For creating the pmtiles it's still better to use tippecanoe, but I don't know of a good way to keep the styles maintained.

**Comment by jaanli** [comment]
Awesome, good to know — thank you Kyle! Will use tippecanoe for now.

**Comment by kylebarron** [comment]
This is not really feasible as such. To export to protomaps, you need to have vector tiles, and there are no vector tiles anywhere throughout lonboard. Alternative options like exporting directly to HTML exist, but for protomaps/pmtiles specifically, you're going to want to use something like tippecanoe.
