### ISSUE TITLE
DataFilterExtension bug - 'get_filter_value' trait of a ScatterplotLayer instance expected filter_size (3) to match 2nd dimension of numpy array

### ISSUE THREAD

**Issue by jaanli** [developmentseed/lonboard#363]
## Context

Need to make several dashboards that have filtering linked to a map (https://github.com/developmentseed/lonboard/issues/353).

## Issue

Cannot use DataFilter extension: getting this error -

```
TraitError: The 'get_filter_value' trait of a ScatterplotLayer instance expected filter_size (3) to match 2nd dimension of numpy array, not the ndarray array([[12500.],
```

To reproduce: https://github.com/jaanli/lonboard/blob/example-american-community-survey/examples/american-community-survey.ipynb

## Acceptance-Criteria
Mapping various census variables and filtering using them for exploratory data analysis and understanding social value + capital deployment using our tax dollars.

**Comment by kylebarron** [comment]
You're passing
```py
filter_extension = DataFilterExtension(filter_size=3)
```
If you're filtering on one column you need to remove that or set to `1` (the default)

Aside: We should probably create a bug-specific issue ticket format.

**Comment by kylebarron** [comment]
Additionally you only need to create a multi-dimensional array when filter_size > 1, so you don't need the `np.column_stack`

**Comment by jaanli** [comment]
Awesome, figured it was something simple. Thank you Kyle!!

**Comment by jaanli** [comment]
Small note: instead of `filter_size`, would a rename to `num_filters` be viable? 

(Coming from machine learning, 'size' in variable names tend to be for other things.)

**Comment by jaanli** [comment]
Reopening this in case others run into this too: 

After fixing the `filter_size` parameter, I am unable to see the output:

In VS Code (seems like a separate issue):

![image](https://github.com/developmentseed/lonboard/assets/5317244/54cbd325-08dd-4aef-a104-48196c35d749)

In Jupyter notebook on Chrome (started with `jupyter notebook`):

<img width="998" alt="image" src="https://github.com/developmentseed/lonboard/assets/5317244/b58eb06a-5dca-4da2-9562-de62984e675c">

Any idea how to fix the display of the filters? 

Getting closer! Super exciting :D

**Comment by jaanli** [comment]
Fixed! Had to:

* restart the Jupyter kernel to get it working in VS Code
* pass in a single slider instead of a MultiRangeSlider (was getting size mismatch errors otherwise that I couldn't figure out - could add different error messages when someone tries to pass a single slider to a MultiRangeSlider as a nice-to-have?)

Thank you!!

<img width="522" alt="image" src="https://github.com/developmentseed/lonboard/assets/5317244/0dd0329f-b7b9-416b-aee3-57a2a29865a0">

Super exciting!!

**Comment by emmalu** [comment]
> Aside: We should probably create a bug-specific issue ticket format. cc @emmalu

💯 Will do!

**Comment by kylebarron** [comment]
> Small note in case this is under active development: instead of `filter_size`, would a rename to `num_filters` be viable? 

I agree that I don't love `filter_size`, but that's the [term used by upstream deck.gl](https://deck.gl/docs/api-reference/extensions/data-filter-extension#constructor) and I'm reluctant to remove this consistency. We try to document this in the API docs https://developmentseed.org/lonboard/latest/api/layer-extensions/data-filter-extension/#lonboard.layer_extension.DataFilterExtension.filter_size. (Thought it is a little unclear the distinction between constructor parameters and layer parameters in the docs)
