### ISSUE TITLE
Update README to include notes on using the new issue templates

### ISSUE THREAD

**Issue by emmalu** [developmentseed/lonboard#385]

**Comment by kylebarron** [comment]
I'm not sure if documentation on the `README` for the issue templates is needed; anyone who creates a new issue will see the issue templates then, right?
<img width="690" alt="image" src="https://github.com/developmentseed/lonboard/assets/15164633/568c9ed8-7b84-4e83-a21e-6a88889ab40a">

**Comment by emmalu** [comment]
Point taken!
