### ISSUE TITLE
lonboard within quarto?

### ISSUE THREAD

**Issue by shriv** [developmentseed/lonboard#473]
This is more of a question rather than a request for an epic! My use case is plotting traffic volumes on every street (technically "link" i.e. segments between intersections) in New Zealand within an HTML document generated by `quarto`. The data is too big to be rendered comfortably by `leaflet`-based libraries and I have to filter the data considerably to view an interactive output.

I'm wondering if `lonboard` can be used within a `quarto` document to visualise the full dataset? I see that `lonboard` can be used with `shiny` but most of my other visualisations can be output as a simple static HTML and hosted on Gitlab Pages so this option would be preferable :-)

**Comment by kylebarron** [comment]
I'm not familiar with using quarto in this way. Does [`to_html`](https://developmentseed.org/lonboard/latest/api/map/#lonboard.Map.to_html) do what you want? That saves the HTML as a file on disk. Or do you want to render the HTML with IPython as a static HTML?

**Comment by shriv** [comment]
The latter. I normally render the quarto document within a single html. The rendering engine for python in quarto is Jupyter and I can even render a `ipynb` file with quarto.. Maybe it will all be fine! Apologies, I normally use R with quarto and I haven't used it as extensively with python. I'll have a bit of a tinker and write back here :-)

**Comment by kylebarron** [comment]
You can try using `IPython.display.core.HTML()` like I do in this PR https://github.com/developmentseed/lonboard/pull/474

**Comment by shriv** [comment]
Many thanks @kylebarron..! I will try that as well 👍

**Comment by shriv** [comment]
Got a `lonboard` map running within quarto!
```
# this was needed because I'm using poetry within a nix environment
export QUARTO_PYTHON=$(which python)
# render the qmd file to html
quarto render test.qmd
```

However, it is a bit slow for all the links in the full country so I'm going to move the project to a shiny app. 

![image](https://github.com/developmentseed/lonboard/assets/3827179/61b2c3a6-7f3e-4332-b39a-46bcae879b06)

**Comment by arthurgailes** [comment]
@shriv how did you get quarto to output the HTML properly?

**Comment by shriv** [comment]
@arthurgailes I just had the following in `test.qmd` before I ran `quarto render test.qmd`. 

```
---
title: "Lonboard test"
execute:
  echo: false
format: 
  html: 
    self-contained: true
jupyter: python3
---

```{python}
# importing packages
import pandas as pd
import geopandas as gpd
import lonboard
from IPython.display import display, HTML

# geopandas option
gpd.options.io_engine = "pyogrio"
```


```{python}
network = gpd.read_file("data/network.gpkg")
car_vols = pd.read_csv("data/volumes_car_hourly.csv")
# join volume data to network
network_vols = network.merge(car_vols)
```

```{python}
layer = lonboard.PathLayer.from_geopandas(
    network_vols,
    width_min_pixels=0.8)
map_ = lonboard.Map(layers=[layer])
map_
```


```†

**Comment by arthurgailes** [comment]
Thank you very much @shriv.

@kylebarron This works for very simple maps, but I don't think the `to_html` method is carrying the anywidget.js import with it; message: `/anywidget.js (404: Not Found)`. 

Adapted from the example above for ease:

```
---
title: "Lonboard test"
format:
  html:
    embed-resources: false
jupyter: python3
---

```{python}
# importing packages
import pandas as pd
import geopandas as gpd
import lonboard
from IPython.display import display, HTML

sample_data = gpd.read_file(
    "https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/geojson/vancouver-blocks.json")

layer = lonboard.PolygonLayer.from_geopandas(
    sample_data
)
map_ = lonboard.Map(layers=[layer])
map_
```

**Comment by arthurgailes** [comment]
@shriv that works, thank you very much.
