### ISSUE TITLE
PathStyleExtension in lonboard

### ISSUE THREAD

**Issue by shriv** [developmentseed/lonboard#484]
As noted in #473 my use case is plotting link volumes on NZ roads. One "feature" of the road geometries (which come from OpenStreetMap) is that lane geometries lie on top of each other. This doesn't look good in the visualisation so we want to split paths with some offset. One fix seems to be the `deck.gl` `PathStyleExtension` with the `offset:true` option. I was wondering if there is a way to include this in a `lonboard` map even though it is not available in the [current set](https://developmentseed.org/lonboard/latest/api/layer-extensions/)? 

```
new deck.PathLayer({
      widthMinPixels: 1,
      capRounded: true,
      data: pathData,
      getPath: (d) => d.path,
      getColor: (d) => d.color,
      getWidth: (d) => d.width,
      getOffset: -0.5,
      extensions: [
        new deck.PathStyleExtension({
          offset: true
        })
      ],
      parameters: {
        depthTest: false
      }
    })
```

**Comment by kylebarron** [comment]
Yes it definitely makes sense to add that to lonboard. 

Do you think you'd be able to try to implement it? It should largely be straightforward if you look at how the other extensions are implemented

**Comment by shriv** [comment]
Yep, I can definitely give it a go :-)

**Comment by kylebarron** [comment]
Closed by https://github.com/developmentseed/lonboard/pull/487
