### ISSUE TITLE
[BUG] Unable to change the basemap_style

### ISSUE THREAD

**Issue by brianmcdonald** [developmentseed/lonboard#485]
## Context

After reading through the documentation and examples I am unable to change the basemap_style to 'DarkMatter'.
The following code displays a map, but just removes all basemap's rather than replacing the default one with Carto's DarkMatter.

```
fires = ScatterplotLayer.from_geopandas(gdf)
map = Map(layers=[fires], _height=800, basemap_style = "DarkMatter")
fires.get_fill_color = "#eb0000"
fires.radius_scale = 500
map
```

It's almost certainly an issue of me not understanding the API docs on basemap_style, but it would be helpful to have some sample code or to show one of the examples with a different basemap.

## Resulting behaviour, error message or logs

**Describe what happened:**
using the `basemap_style = "DarkMatter"` option removes all baseman's rather than changing it from the default

## Environment

- OS: MacOS 14.1
- Browser: Safari
- Lonboard Version: 0.8.0]

**Comment by kylebarron** [comment]
The string is not the _name_ of the basemap style; it's the _URL_ where the style is located. You can use `CartoBasemap` as a helper to not need to recall the URL.

```py
from lonboard.basemap import CartoBasemap
from lonboard import Map

Map(layers=[], basemap_style=CartoBasemap.DarkMatter)
```

<img width="523" alt="image" src="https://github.com/developmentseed/lonboard/assets/15164633/853e005f-1281-4079-be5f-8470211a9ce1">


if you print the value of that enum variant, you can see the URL it points to:
```py
print(CartoBasemap.DarkMatter.value)
# https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json
```

So it would also work if you passed that str into the `Map` directly


```py
from lonboard.basemap import CartoBasemap
from lonboard import Map

Map(
    layers=[],
    basemap_style="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json",
)
```

**Comment by kylebarron** [comment]
We can probably make a better error message by asserting that the str input to `basemap_style` is a URL of some kind
