### ISSUE TITLE
Invert layers order in `split_mixed_gdf` function

### ISSUE THREAD

**Issue by RaczeQ** [developmentseed/lonboard#513]
What do you think about changing the order of gdfs and subsequently layers to keep points and lines on top of polygons? It seems natural to me, but I don't know if it's viable to do so.
https://github.com/developmentseed/lonboard/blob/b2ca1929c4de491c2347455c0b8717de6fc78fb1/lonboard/_utils.py#L143-L161

```python
viz(
    result_gdf.geometry, # since points are being split first, they land as first layer on the bottom
    # optional styling
    scatterplot_kwargs=dict(get_fill_color="#5c53a5"),
    path_kwargs=dict(get_color="#eb7f86"),
    polygon_kwargs=dict(stroked=False, get_fill_color="#f3e79b"),
    map_kwargs=dict(basemap_style=basemap.CartoBasemap.VoyagerNoLabels),
)
```
![image](https://github.com/developmentseed/lonboard/assets/17250607/a1fa6cc3-cf75-40fe-9151-51153e1129d7)

**Comment by RaczeQ** [comment]
I've created a #516 PR for this issue 😉

**Comment by kylebarron** [comment]
Closed by https://github.com/developmentseed/lonboard/pull/516
