### ISSUE TITLE
Google Colab crashes for large datasets

### ISSUE THREAD

**Issue by adamekcerv** [developmentseed/lonboard#514]
Hi,

I would like to use a 'lonboard' in Google Colab to visualize a GeoDataFrame ('gdf'). The code runs without any errors, but no output is displayed, even though it works on my local PC. What could be the issue?

**Comment by kylebarron** [comment]
I know when I tested Colab originally that there were issues with rendering large datasets. Can you see _any map_ even one without any data? If so, it's likely issues on Colab's side with dropping the connection for large datasets

**Comment by kylebarron** [comment]
@Melda-s looking at your notebook, it also crashes for me during the cell that constructs the layer. It looks like that is the same issue I referenced before, where Colab crashes when trying to send large amounts of data outside of the Python session. At its core, this is a colab issue that's hard to work around. We could potentially export user settings for how big each data chunk should be from Python to the frontend, but that's an unideal workaround

**Comment by kylebarron** [comment]
This isn't really possible for us to reliably work around. It's Colab's core issue that it's unable to manage a stable connection for large data to move from Python to JS.
