### ISSUE TITLE
Understanding fly_to() and set_view_state()

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/lonboard#518]
### Discussed in https://github.com/developmentseed/lonboard/discussions/517

<div type='discussions-op-text'>

<sup>Originally posted by **z-clement** May 13, 2024</sup>
Hi,

I'm working with lonboard for some large spatial data visualizations, and it's been a great tool so far! I'm trying to add a `fly_to()` method to change the view state of the map. I pass in `longitude`, `latitude`, and `zoom` to `fly_to()` and the map view state changes, but not in the way I'd expect.

The basemap changes views to the correct location, however the data don't update, instead it's fixed on the screen, seemingly drawn in the same exact way as when the map first loaded. Additionally, the map stops being interactive after that call, and I get thrown the following error: `TypeError: ViewState.__new__() got an unexpected keyword argument 'transitionDuration'`.

I've tried using `set_view_state()` as well, and while it doesn't throw an error, my plotted data completely disappear after the basemap changes, and it stops being interactive.

Is this a bug, or am I not understanding the use cases of these two functions? Thanks for any insight! (Also am unsure if discussions is the place for this, can repost elsewhere if that fits better.)</div>

**Comment by kylebarron** [comment]
This definitely sounds like a bug. Do you happen to have a minimal reproduction case here?

**Comment by z-clement** [comment]
Here's a quick one based on the North American roads example in the documentation:
`import geopandas as gpd`
`import palettable.colorbrewer.diverging`
`from lonboard import Map, PathLayer`
`from lonboard.colormap import apply_continuous_cmap`
`url = "https://naciscdn.org/naturalearth/10m/cultural/ne_10m_roads_north_america.zip"`
`gdf = gpd.read_file(url)`
`gdf = gdf[gdf["state"] == "California"]`
`layer = PathLayer.from_geopandas(gdf, width_min_pixels=0.8)`
`m = Map(layers=[layer])`
`m`

That generates the map, then the following throws the error:
`coords = gdf.to_crs(epsg=3857).centroid.to_crs(epsg=4326)`
`m.fly_to(longitude=coords.x, latitude=coords.y, zoom=13)`

With this being the error:
`TypeError: ViewState.__new__() got an unexpected keyword argument 'transitionDuration'`

**Comment by kylebarron** [comment]
`coords.x` and `coords.y` are each a Series, not a single integer:

<img width="414" alt="image" src="https://github.com/developmentseed/lonboard/assets/15164633/0ad500c5-5844-4b41-add4-43f5a226f1be">

If you use a single integer, it works:

https://github.com/developmentseed/lonboard/assets/15164633/dd5123f6-7da3-4234-8e37-bbfc1755b0ae
