### ISSUE TITLE
Binder badge for example notebooks

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/lonboard#52]
Can create a binder badge to the repo from this page: https://mybinder.org/; more env docs here: https://mybinder.readthedocs.io/en/latest/introduction.html

**Comment by kylebarron** [comment]
I'll look into this, but one thing to try is subsetting the data to a smaller region before plotting.

Binder should be picking up the requirements.txt in the `.binder` folder: https://github.com/developmentseed/lonboard/blob/main/.binder/requirements.txt

And additionally we try to pre-cache binder docker images so that it'll be fast to load for the user https://github.com/developmentseed/lonboard/blob/main/.github/workflows/build-binder-image.yml (ref https://github.com/jupyterhub/repo2docker-action#cache-builds-on-mybinderorg)

On Friday, I believe the point notebook was working consistently for me (even with all the data) while the linestring example was crashing the kernel for an unknown reason

**Comment by batpad** [comment]
Hmm today it seems like the build step on Binder is failing, which was working yesterday: https://mybinder.org/v2/gh/developmentseed/lonboard/HEAD?labpath=examples%2Finternet-speeds.ipynb

@kylebarron do you know if this looks like something you changed in `lonboard` or something on the Binder side? I've tried 2-3 times today and the build has consistently failed for me with:

```
Step 50/50 : CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]
 ---> Running in 688cfbefda2f
Removing intermediate container 688cfbefda2f
 ---> c726de31344b
{"aux": {"ID": "sha256:c726de31344b99108d27e5999ad6ea6f566f2ddd6b89876e821aeb9850a8a7b1"}}Successfully built c726de31344b
Successfully tagged gesiscss/binder-r2d-g5b5b759-developmentseed-2dlonboard-b99df7:42d90bb6ecd275afb55b15b6d6d462133733eec8
Error during build: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
```

**Comment by kylebarron** [comment]
I'm 99% sure `Read timed out` is a binder issue and not ours. I've seen it randomly a few times myself.
