### ISSUE TITLE
[BUG] None default get_line_color in PolygonLayer not respected

### ISSUE THREAD

**Issue by ncclementi** [developmentseed/lonboard#541]
## Context

I'm plotting a PolygonLayer in a map, I have something like:

```python
pol = PolygonLayer.from_geopandas(
    my_polygon, get_fill_color="orange", opacity=0.1
)
mh = Map(
    [pol ], 
)
```

and when displayed on the map. I see a line and I which not to. 

![Screenshot 2024-06-10 at 7 22 01 PM](https://github.com/developmentseed/lonboard/assets/7526622/6fa02952-1e2f-4d33-920a-addc47951db5)

## Environment

- OS:  MacOS Sonoma 14.5
- Lonboard Version: 0.9.1

## Steps to reproduce the bug

This is part of a long workflow, trying to transform this blog to use just plain lonboard and avoid leafmap https://ibis-project.org/posts/ibis-duckdb-geospatial/ the code is the last cell, and I converted into: 

```python
broad_station_layer = ScatterplotLayer.from_geopandas(
    broad_station_gdf, get_fill_color="orange", get_radius=5
)

broad_station_zone_layer = PolygonLayer.from_geopandas(
    broad_station_zone, get_fill_color="orange", opacity=0.1
)

h_near_broad_layer = ScatterplotLayer.from_geopandas(
    h_near_broad_gdf, get_fill_color="red", get_radius=5
)

h_street_layer = PathLayer.from_geopandas(
    h_street_gdf, get_color="blue", opacity=0.5, get_width=2
)

streets_layer = PathLayer.from_geopandas(streets_gdf, get_color="grey", opacity=0.3)

mh = Map(
    [
        broad_station_layer,
        broad_station_zone_layer,
        h_near_broad_layer,
        h_street_layer,
        streets_layer,
    ], 
    view_state={"longitude": -74.01066, "latitude": 40.7069, "zoom": 16}
)
mh
```

**Comment by kylebarron** [comment]
👋 I'm back from vacation.

[The default for `get_line_color`](https://developmentseed.org/lonboard/latest/api/layers/polygon-layer/#lonboard.PolygonLayer.get_line_color) is `[0, 0, 0, 255]`, which represents black. To avoid drawing a line, set [`stroked: False`](https://developmentseed.org/lonboard/latest/api/layers/polygon-layer/#lonboard.PolygonLayer.stroked)

**Comment by ncclementi** [comment]
Oh nice, I missed that on the docs. Ended up leaving it as it was, so we could merged a PR, but now this blog https://ibis-project.org/posts/ibis-duckdb-geospatial/ is using `lonboard` all the way. 

I know this is out of scope, but there is no way to get automatic zoom on a layer right? I had to use `view_state` and provide specific lat and lon to get the nice zoom on the plot.

**Comment by kylebarron** [comment]
There's currently automatic zoom on the map but not on each layer. Can you create a new issue for this? We [store a bbox and weighted centroid on each layer](https://github.com/developmentseed/lonboard/blob/5560ead37e4bf02b8a39ef08b631c5b2f7108754/lonboard/_layer.py#L74-L76), so we could potentially implement a "zoom to layer extent" method pretty easily.

**Comment by ncclementi** [comment]
xref: https://github.com/developmentseed/lonboard/issues/544
