### ISSUE TITLE
Why "Input being reprojected to EPSG:4326 CRS"?

### ISSUE THREAD

**Issue by ncclementi** [developmentseed/lonboard#566]
I'm plotting multiple layers of a Map and I get a bunch of warning saying:

`Input being reprojected to EPSG:4326 CRS` . Why is that warning showing up? I think a more explanatory message would be helpful.

**Comment by kylebarron** [comment]
That warning is shown whenever the input data contains a CRS that is not EPSG:4326. I added that warning because I believed it was useful to be explicit about reprojecting user data. Lonboard currently is only able to render data in EPSG:4326 projection

**Comment by ncclementi** [comment]
Thanks, that's very helpful. I think having a warning that is slightly more descriptive would help. Something like... 

"Input being reprojected to EPSG:4326 CRS. At the moment lonboard is only able to render data in EPSG:4326"

Happy to make a PR at some point this week if you think some version of the expanded warning message is useful.
