### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/lonboard#568]
At the moment, we have Prettier formatting checks and TypeScript checks, but not ESLint checks. Adding ESLint would help us improve JavaScript code quality and maintain consistency across the codebase.

cc @kylebarron @batpad

**Comment by kylebarron** [comment]
I'm happy to do this. Do you have any opinions about newer alternatives like [oxlint](https://github.com/oxc-project/oxc)?

**Comment by vgeorge** [comment]
This is the first time I'm hearing about oxlint, it looks very interesting. My main concern is whether it has good integration with VSCode. If the development experience is similar to using ESLint, I think we can give it a try.

**Comment by vgeorge** [comment]
@kylebarron I looked into oxlint, it seems very bleeding edge. I created an `oxlintrc.json` file with the `no-console` and `no-unused-vars` rules enabled, but the oxc VS Code extension isn't able to pick it up.

**Comment by kylebarron** [comment]
That's fine; a PR to add eslint would be great
