### ISSUE TITLE
Support different Arrow chunking across main table and accessors

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/lonboard#611]
I should be able to rechunk accessors as needed to work with the main table.

I believe @abarciauskas-bgse was hitting this issue with colormap data, where the `get_fill_color` had no internal chunks

**Comment by abarciauskas-bgse** [comment]
Thanks @kylebarron if you end up working on this let me know if I can look over your virtual shoulder 🦆

**Comment by kylebarron** [comment]
It's something I need to handle if I want more end users using Arrow input. Maybe at the end of next week if you have time we can sync and I can go over how I fix it.

**Comment by kylebarron** [comment]
Assigning this to 0.10 because if we're working with Arrow data more and more, it's really confusing if this silently fails due to chunking issues.
