### ISSUE TITLE
[BUG] lonboard and maplibre does not work together

### ISSUE THREAD

**Issue by giswqs** [developmentseed/lonboard#640]
## Context

What results were you expecting? <br/>

When installing lonboard and [maplibre](https://github.com/eodaGmbH/py-maplibregl) in the same conda env, lonboard does not work. The map does not render. The Chrome developer console show `Error: deck.gl - multiple versions detected: 9.0.16 vs 8.9.35`. The maplibre renders just fine. 

Relevant issue: https://github.com/visgl/deck.gl/issues/4909

## Resulting behaviour, error message or logs

![image](https://github.com/user-attachments/assets/704e7042-79ee-4a22-8130-831c2941117d)

## Environment

- OS: Linux
- Browser: Chrome Version 129.0.6668.58 (Official Build) (64-bit)
- Lonboard Version: 0.9.3

## Steps to reproduce the bug

```bash
conda create -n test python=3.12
conda activate test
conda install -c conda-forge lonboard maplibre jupyterlab
```

**Comment by kylebarron** [comment]
You can't have multiple deck.gl versions loaded onto the page. You would need some sort of isolation on the Jupyter side in the browser, which I don't think exists. 

This is not possible for me to fix; I believe the only solution is to not have them both installed.
