### ISSUE TITLE
MovingPandas Intergration 

### ISSUE THREAD

**Issue by lebuu-eu** [developmentseed/lonboard#682]
## Context

This is my first time creating a bug report. I was making the trips_layer to recreate the example code. I was expecting the creation of trip_layer but I got an error. <br/>

## Error Message
**AttributeError: `np.alltrue` was removed in NumPy 2.0 release. Use `np.all` instead.**

![image](https://github.com/user-attachments/assets/5d8ab9fa-8e72-4337-babd-b1d8032002c2)

## Environment

- OS: Windows 11 Enterprise
- Browser: Safari
- Lonboard Version: 0.10.0

## Steps to reproduce the bug

I followed the same step from the example.

After downgrading numpy to version 1.26.4 everything worked as expected. 
   <br/>
   ...

**Comment by kylebarron** [comment]
Thanks for the report! I published 0.10.2, and it should be on PyPI in a few minutes.
