### ISSUE TITLE
[BUG] v0.10.1 import fails in Google Collab notebooks

### ISSUE THREAD

**Issue by willemarcel** [developmentseed/lonboard#684]
## Context

When I install lonboard 0.10.1 in a Google Collab, the import fails.

## Resulting behaviour, error message or logs

**Describe what happened:**

```
TypeError                                 Traceback (most recent call last)

[<ipython-input-2-898f83bc3a04>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from lonboard import Map

4 frames

[/usr/local/lib/python3.10/dist-packages/lonboard/traits.py](https://localhost:8080/#) in <module>
   1076 
   1077 
-> 1078 class VariableLengthTuple(traitlets.Container[Tuple[T, ...]]):
   1079     """
   1080     An instance of a Python tuple with variable numbers of elements of the same type.

TypeError: 'type' object is not subscriptable
```

## Environment

- Lonboard Version: 0.10.1
- Runtime: CPU

## Steps to reproduce the bug

Describe the actions that led you to encounter the bug. Example:

1. imported lonboard into a new notebook
2. add a new code line with `from lonboard import Map`

**Comment by kylebarron** [comment]
What version of traitlets is installed?

**Comment by willemarcel** [comment]
> What version of traitlets is installed?

traitlets is 5.14.3

**Comment by kylebarron** [comment]
Aha, no it's not!

<img width="275" alt="image" src="https://github.com/user-attachments/assets/96d7f1be-74e5-4e06-b42f-853a74e44234">

This is annoying but apparently it's not possible to update the traitlets version on Colab

**Comment by spatialthoughts** [comment]
I am also running into this in Colab. Switching to the old version makes it work for now. `!pip install lonboard==0.9.3` but would be good to make the newer versions work in Colab.
