### ISSUE TITLE
[BUG] `apply_continuous_cmap` mutates the column it operates on

### ISSUE THREAD

**Issue by ajfriend** [developmentseed/lonboard#690]
## Context

Maybe I'm doing something dumb, but it looks like `apply_continuous_cmap` mutates the column it is operating on, when I would expect it to leave it unchanged. See the example notebook here:

https://gist.github.com/ajfriend/40b0d5a2b8d7ea02fa8f35574aab65b7

This only seems to happen on pandas Series, but not numpy arrays. It happens for both palettable and matplotlib colormaps.

## Environment

- OS: macos 14.6
- Browser: Chrome
- Lonboard Version: `0.10.3`

## Steps to reproduce the bug

Shown in notebook above.

**Comment by kylebarron** [comment]
`apply_continuous_cmap` is pretty much a one-line wrapper around matplotlib: https://github.com/developmentseed/lonboard/blob/b32d9a5483bac203b2db8b327d1ac750076c5419/lonboard/colormap.py#L131-L136

can you check if applying the matplotlib `cmap` on your data also gives the same behavior? Possibly check with the latest version of `matplotlib` too?

**Comment by ajfriend** [comment]
<img width="420" alt="image" src="https://github.com/user-attachments/assets/d4e569e6-05a1-4794-b10a-9d07964fb2b5">

Ok, yeah. I guess this is a problem with `matplotlib` then. Weird!

**Comment by ajfriend** [comment]
https://github.com/matplotlib/matplotlib/issues/29002

**Comment by kylebarron** [comment]
Given https://github.com/matplotlib/matplotlib/issues/29002#issuecomment-2426926411 I'll close this
