### ISSUE TITLE
Multiple docstrings reference geoarrow.rust.core instead of geoarrow.rust.io

### ISSUE THREAD

**Issue by ATL2001** [developmentseed/lonboard#702]
There are a [few places](https://github.com/developmentseed/lonboard/blob/d5bc98fbbbe382d142dc8640487a0feecea1ea3b/lonboard/_layer.py#L998C5-L998C48) which mention importing functionality from geoarrow.rust.core which seems to have been moved to geoarrow.rust.io and [this line](https://github.com/developmentseed/lonboard/blob/d5bc98fbbbe382d142dc8640487a0feecea1ea3b/docs/ecosystem/geoarrow.md?plain=1#L12) that mentions the depreciated GeoTable.  

I'd be happy to put in a PR to update the docstrings and remove the reference to GeoTable

**Comment by kylebarron** [comment]
Ah, thanks for the note! Yes, a PR to update those references would be greatly appreciated!
